version: "3.7"

services:
  mdbook:
    # v0.3.6 and newer seems not to be built correctly.
    image: peaceiris/mdbook:v0.3.5
    command: ['serve', '--hostname', '0.0.0.0']
    init: true
    volumes:
      - .:/book
    ports:
      - 3000:3000
      - 3001:3001
