# See https://github.com/dependabot/dependabot-core/issues/2268#issuecomment-831376155
name: Auto Merge

on:
  workflow_run:
    workflows:
      - Pull Request
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/github-script@v5
        with:
          # Use PAT in order to invoke other workflows.
          github-token: ${{ secrets.BOT_GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
            });
            if (pr.data.user.login !== 'dependabot[bot]') {
              console.log(`Condition unmet: user: "${pr.data.user.login}"`);
              return;
            }
            if (!pr.data.title.startsWith('build(deps):') && !pr.data.title.startsWith('build(deps-dev):')) {
              console.log(`Condition unmet: title: "${pr.data.title}"`);
              return;
            }
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.workflow_run.pull_requests[0].number,
            });
            console.log('Merged successfully');
